// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BUtPUiUmX7AqY_utxir1JyjX2GEwVDM',
    appId: '1:1049729394052:web:584a3fbccfd77efbfc29d1',
    messagingSenderId: '1049729394052',
    projectId: 'e-commerce-bbc53',
    authDomain: 'e-commerce-bbc53.firebaseapp.com',
    storageBucket: 'e-commerce-bbc53.firebasestorage.app',
    measurementId: 'G-ESB1KTMX6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2yChls-t40LfCBQQmDeUxc3CuFN9YOPk',
    appId: '1:1049729394052:android:2387aa5760ca6620fc29d1',
    messagingSenderId: '1049729394052',
    projectId: 'e-commerce-bbc53',
    storageBucket: 'e-commerce-bbc53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2mgdiBz822PeS6Gl45Gxrvtank12APBo',
    appId: '1:1049729394052:ios:ea03d1d07f05d262fc29d1',
    messagingSenderId: '1049729394052',
    projectId: 'e-commerce-bbc53',
    storageBucket: 'e-commerce-bbc53.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2mgdiBz822PeS6Gl45Gxrvtank12APBo',
    appId: '1:1049729394052:ios:ea03d1d07f05d262fc29d1',
    messagingSenderId: '1049729394052',
    projectId: 'e-commerce-bbc53',
    storageBucket: 'e-commerce-bbc53.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6BUtPUiUmX7AqY_utxir1JyjX2GEwVDM',
    appId: '1:1049729394052:web:1afb7dd73660c8aafc29d1',
    messagingSenderId: '1049729394052',
    projectId: 'e-commerce-bbc53',
    authDomain: 'e-commerce-bbc53.firebaseapp.com',
    storageBucket: 'e-commerce-bbc53.firebasestorage.app',
    measurementId: 'G-Y7HX34H6VR',
  );
}
